### ISSUE TITLE
Update website header.

### ISSUE THREAD

**Issue by doritg** [Gizra/Gizra#167]
See link below with psd. zip also includes modification in About Us fonts, etc. 

https://drive.google.com/drive/folders/0B0RkPEujepS0flFqRFZzUWNwODJfZWtsaHNpbmo2YXNSTkxsZEpGVTVieWp4ZUdzM1hZdjg

**Comment by nader77** [comment]
@doritg Please share permissions to this folder with me, Thanks.

**Comment by nader77** [comment]
@doritg I'm gonna sum up our emails here in this issue, Let's keep all further communication here in this issue

* For now, Update the header with a static image (Remove carousel).
* Only the balloons will have movements.
* Will update the fonts of the website and all the changes seen in the following PSD files:
https://www.dropbox.com/sh/y0c1lhw3uqez0cq/AADOXt7YiWBSUbvbi0r0-PaSa?dl=0

CC: @niryariv

**Comment by niryariv** [comment]
@nader77 that's correct to my understanding - in any case don't change the live site yet, we'll go over the page when it's up and see if there are changes needed

**Comment by doritg** [comment]
@nader77 Great, thanks

**Comment by doritg** [comment]
@nader77 correct and agreed with Nir about live site. Can enarge photo if needed, but logo strip below should show at least top row. Great, thanks

**Comment by nader77** [comment]
I will not upload anything to the live site, I will create a PR and screenshot all the changes for your review before.

**Comment by doritg** [comment]
Thanks
