### ISSUE TITLE
New "About Us" text

### ISSUE THREAD

**Issue by niryariv** [Gizra/Gizra#178]
@amitaibu thoughts? 

Founded in 2009, Gizra LTD is a twenty person software development shop specializing in Open Source technologies.

Gizra created and maintains several key Drupal modules used in major websites such as the White House, The Economist, Energy.gov and others, and is a contributor to Drupal 8 core. Our Open Source work led to client engagements with organizations such as the European Commission, Harvard University and the United Nations. 

We put a high emphasis on sharing our knowledge and speak regularly at software development conferences worldwide. 

We are committed to continually reviewing our process and our work, being open and honest in our code and personal relations and never stop seeking a better way.

**Comment by amitaibu** [comment]
:+1:

**Comment by niryariv** [comment]
@nader77 - last change for the conference.
