### ISSUE TITLE
Redesign: Team page.

### ISSUE THREAD

**Issue by YuriGizra** [Gizra/Gizra#200]
#195

**Comment by YuriGizra** [comment]
@amitaibu,
Is this page should be resized to 1336px like homepage?

**Comment by YuriGizra** [comment]
@kerensoref,
Is this page should be resized to 1336px like homepage?

**Comment by kerensoref** [comment]
Yep. https://www.dropbox.com/s/ry9mf4jnsovpold/team1366.psd?dl=0
