### ISSUE TITLE
Homepage clients links + split to small files

### ISSUE THREAD

**Issue by niryariv** [Gizra/Gizra#237]
this should be shown on hover, instead of the current "visit project" text (I'm assigning to @YaronMiro to get it done quickly but @RachelBaram please check to see if you want to do any changes to the text)

[White House] [WhiteHouse.gov](http://WhiteHouse.gov) discussion and collaboration features are powered by the high profile Gizra-developed Drupal modules *Organic Groups* and *Message Stack*

[Harvard] Harvard University teamed with Gizra to build [OpenScholar](http://openscholar.harvard.edu/), an Open Source web publishing solutions powering over 6,000 staff and faculty websites

[Acquia] Acquia worked with Gizra to develop [Drupal Commons](https://www.acquia.com/solutions/digital-experience-management/community), a social-focused Drupal distribution

[Commerce Guys] Commerce Guys collaborated with Gizra to build [Commerce Kickstart](https://commerceguys.com/product/commerce-kickstart), an eCommerce focused Drupal Distribution

[EC] Collaborated  in the development of the Capacity4Dev and Projects4Dev websites that support  the European Commission management of billions of Euros’ worth of international development projects.

[Grammy] Gizra helped The Recording Academy build GrammyPro, its internal members’ network, which uses the *Organic Groups* and *Message* modules to power advanced social features

[WIX] Wix hired Gizra to build feed features for its platform, powering over 70 million websites

These don't exist on the site now but we might consider adding them later:

[MSNBC] MSNBC.com makes use of Gizra-developed Organic Groups module to power its user participation forums

[Goethe University Frankfurt] Gizra developed the Library of Haskala website for the Goethe University Frankfurt

**Comment by RachelBaram** [comment]
Reviewed text. Good as-is for now.

**Comment by YaronMiro** [comment]
@niryariv 
Please provide shorter text versions. It doesn't look good when we have a lot of text.
The `acquia` and `wix` are a good examplse for the correct amount of text.

* Clients logos
![selection_216](https://cloud.githubusercontent.com/assets/3907724/11767001/f3ac0d8c-a1a6-11e5-95bc-7b2a05834483.png)

* Clients text
![selection_215](https://cloud.githubusercontent.com/assets/3907724/11767002/f58a795e-a1a6-11e5-9351-e677d5db45eb.png)

**Comment by RachelBaram** [comment]
@YaronMiro  - It was difficult to shorten them down to the length of WIX and Acquia. How does it look with this length? If it is still an issue, I will do an overhaul of the text to keep it under 15 words.

[White House] Discussion & collaboration features powered by the high profile Gizra-developed Drupal modules Organic Groups and Message Stack.

[Harvard] Teamed up to build OpenScholar, an Open Source web publishing solutions powering over 6,000 staff and faculty websites.

[Acquia] Acquia worked with Gizra to develop Drupal Commons, a social-focused Drupal distribution.

[Commerce Guys] Collaborated with Gizra to build Commerce Kickstart, an eCommerce focused Drupal Distribution.

[EC] Collaborated in the development of two web solutions that support the management of billions of Euros’ worth of international development projects.

[Grammy] Helped The Recording Academy build GrammyPro, its internal members’ network that uses the Organic Groups and Message modules to power advanced social features.

[WIX] Wix hired Gizra to build feed features for its platform, powering over 70 million websites.

**Comment by RachelBaram** [comment]
An shorter version. @niryariv see if you can live with this and let @YaronMiro know.

[White House] Powered by the high profile Gizra-developed Drupal modules Organic Groups and Message Stack.

[Harvard] Teamed up on OpenScholar, an Open Source web publishing solutions powering over 6,000 academic websites.

[Acquia] Acquia worked with Gizra to develop Drupal Commons, a social-focused Drupal distribution.

[Commerce Guys] Collaborated with Gizra to build Commerce Kickstart, an eCommerce focused Drupal Distribution.

[EC] Collaborated on iCapacity4Dev and Projects4Dev that help manage billions of Euros’ worth of international development projects.

[Grammy] Helped build GrammyPro, an internal network, using the Organic Groups and Message modules to power advanced social features.

[WIX] Wix hired Gizra to build feed features for its platform, powering over 70 million websites.

**Comment by YaronMiro** [comment]
* [ ] Use the full text.
* [ ] Remove the the "visit project" link - links are embedded as a part of the text.
* [ ] On mobile when you touch the logo you will then see the text.
* [ ] On mobile only show a single client on each click (close all of the others).

**Comment by RachelBaram** [comment]
@YaronMiro If you are going to use the full text, here it is with some small edits (mostly adding periods at the end of the sentences).

[White House] WhiteHouse.gov discussion and collaboration features are powered by the high profile Gizra-developed Drupal modules Organic Groups and Message Stack.

[Harvard] Harvard University teamed with Gizra to build OpenScholar, an Open Source web publishing solutions powering over 6,000 staff and faculty websites.

[Acquia] Acquia worked with Gizra to develop Drupal Commons, a social-focused Drupal distribution.

[Commerce Guys] Commerce Guys collaborated with Gizra to build Commerce Kickstart, an eCommerce focused Drupal Distribution.

[EC] Collaborated in the development of the Capacity4Dev and Projects4Dev websites that support the European Commission management of billions of Euros’ worth of international development projects.

[Grammy] Gizra helped The Recording Academy build GrammyPro, its internal members’ network, that uses the Organic Groups and Message modules to power advanced social features.

[WIX] Wix hired Gizra to build feed features for its platform, powering over 70 million websites.

**Comment by niryariv** [comment]
@rachelbaram it is key that we keep the links inside the texts - they send users to the specific URLs of our projects, rather than the main Harvard etc websites.

**Comment by RachelBaram** [comment]
@niryariv  Are you asking me to put back the links that you originally included? I did not intend to take them out. I just copied and pasted the text so I can fix it.
