### ISSUE TITLE
Add another brakepoint  between mobile and desktop

### ISSUE THREAD

**Issue by YaronMiro** [Gizra/Gizra#242]

**Comment by amitaibu** [comment]
@YaronMiro I think a much quicker and less work way would be to simply default to the 1200px. On my laptop (and I suspect also on @niryariv ) it's enough to fix this vertical scroll thing.  What do you think?

<img width="1279" alt="design___web_development___gizra_and_presentation-opsys1_ _amitai_amitais-macbook-pro_ _zsh_ _121x29" src="https://cloud.githubusercontent.com/assets/125707/11825168/bf3cc5fe-a37d-11e5-9b8c-6111e96f7926.png">

**Comment by amitaibu** [comment]
@YaronMiro I'd be happy to tackle this, as this creates a bad experience also on regular (laptop) desktops . I have a feeling that it can be a quick fix with a quick win. Should have probably never gone with this 1336px :/

**Comment by YaronMiro** [comment]
@amitaibu 
Fixed on #266
I Handel it and will upload it today to the live site.
I fixed it as you suggested and It works as expected (Tested on Roy's laptop - 13 inch) - No scroll.
