### ISSUE TITLE
Homepage above the fold text fixes

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#256]
cc @amitaibu @niryariv 

- [x] Add a period after HERE
- [x] Break after "Seriously". Bring "Do it in a" to the next line and adjust extra text down to the 4th line.
- [x] Read our “The About Story”. It’s different. CHANGE TO: Read our “About Story.” It’s different.       Note: The link underline for "About Story." should not include the quotes.

![1](https://cloud.githubusercontent.com/assets/14312543/11808355/b34ceb20-a328-11e5-85ba-6471acd66497.png)

**Comment by YaronMiro** [comment]
Resolved on #266
