### ISSUE TITLE
Text changes for Testimonials 

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#257]
- [x] The person's title should be moved under the names (for three quotes).
- [x] Harvard - Put a period at the end, inside the quotations.
- [x] The National Library - Written incorrectly with mistakes. Here is a fix of the quote currently on the site: “Gizra translated our wishes to technical specifications and to a working product and did so in a timely manner and within budget. Not less important, they remained attentive and captured the needs arising from the different partners.”

@niryariv  Acquia - The quote chosen talks to Drupal specifically. The original quote spoke to the diverse tools that Gizra knows to use. Need to decide what message best aligns with Gizra’s brand. If we want to emphasize the various tools then I will find a way to shorten it for our site.

cc @amitaibu

**Comment by niryariv** [comment]
@RachelBaram - the NLI quote is taken from the source, I didn't want to change the original.

regarding the Acquia quote, ultimately our core expertise and the main reason people pick us is our Drupal ability. Acquia specifically are recognized as *the* Drupal company, so IMHO having them praise us on this is uniquely powerful.

**Comment by RachelBaram** [comment]
@niryariv 
Cool about making the Acquia quote Drupal specific. 
The NLI quote has to be fixed (even if it is from the original text). If you don't feel comfortable changing it, then we should use a different section.

**Comment by niryariv** [comment]
Ok, let's go with the fixed versIon

**Comment by YaronMiro** [comment]
* Final version:

“Gizra translated our wishes to technical specifications and to a working product and did so in a timely manner and within budget. Not less important, they remained attentive and captured the needs arising from the different partners.”

**Comment by YaronMiro** [comment]
Resolved on #266
