### ISSUE TITLE
Updated "About Us" text

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#258]
cc @amitaibu @niryariv 
Please replace with the following: 

Formed in 2009, Gizra Internet Solutions, is a fast growing international software development company with an  extensive track record in site building and content management system configuration and implementation. Gizra is experienced in agile and continuous deployment and is a pioneer in Drupal development and software methodologies.  Gizra is known among its clients as an efficient executor of complex web projects. 

#### What Makes Us Different

Gizra developed a unique work methodology called **_The Gizra Way_**. It’s a culmination of best practices, lessons learned and open source philosophy that we incorporate into our project workflows, saving money and ensuring timely delivery. Our clients’ positive experience is found not only in the excellence of their web solution but in the way we get there. The key elements are:

**True Transparency.**  Client has full access to Gizra’s source repository and task tracking system, viewing code commits as they happen. This means that all of Gizra’s internal communications and actions are in full view to the client. We like it this way because it attains an environment of collaboration,openness and accountability. 

**Effective Communication.** Client is a member of the task tracking system and  is encouraged to fully participate in the development process interacting directly with developers of all levels. All stakeholders stay up to date on progress and decisions making occurs quickly and per the client’s needs and priorities.
   
**Meticulous Execution.** Complete deployment and testing system built into projects from day one, growing as the code does. We use  [**_Shoov_**] (http://shoov.io/), a Gizra developed testing toolkit conceived from our internal best practices. Collaborate with the best designers to ensure design is optimal from visual, interaction and technical standpoint.  The final design is completed with pixel-perfect implementation.

**Invest in Human Assets & Community.** The Gizra Way is also implemented internally with a flat organizational structure, a diligent mentorship program, persistent execution of best practices and an in-house mechanism for continuous improvement.  As pioneers in the Drupal community we regularly present at DrupalCon and DrupalCamp conferences globalwide. Employees are given the opportunity to contribute to the Open Source community on company time.

**Comment by YaronMiro** [comment]
@RachelBaram 
Please update/replace this issues with the latest text you have.
Thanks.

**Comment by RachelBaram** [comment]
ABOUT US
Gizra Internet Solutions Ltd., formed in 2009 and incorporated in the U.S. as Gizra USA, LLC in 2015, is a fast-growing international software development company with an extensive track record in site building and implementation of content management systems. Gizra is experienced in agile and continuous deployment and is a pioneer in Drupal development and other bleeding-edge projects. Gizra is known among its clients as an efficient executor of complex web solutions.

__What Makes Us Different__
Gizra has developed a unique work methodology called *__The Gizra Way.__* It is a culmination of best practices, lessons learned, and open source philosophy that is incorporated into our project workflow, saving our clients money and ensuring the timely delivery of a product. The satisfaction of our clients is found not only in the excellence of their web solution, but in the way we get there. 

The key elements of _The Gizra Way_ are:

__True Transparency.__ Our client has full access to the source repository and task tracking system, viewing code commits as they happen. This means that all of Gizra’s internal communications and actions are in full view to the client. We like it this way because it fosters  an environment of collaboration, openness, and accountability. 

__Effective Communication.__ Our client is a member of the task tracking system and is encouraged to participate fully in the development process, interacting directly with developers of all levels. All stakeholders stay up to date on progress and decision-making occurs in real time according to the client’s needs and priorities.  

__Meticulous Execution.__ A complete deployment and testing system is built into our projects from day one, growing as the code does. We use Shoov, a Gizra developed testing toolkit, which ensures design is optimal from visual, interaction, and technical standpoints. The final design is completed with pixel-perfect implementation.

__Investment in Human Assets & Community.__ _The Gizra Way_ is also implemented internally with a flat organizational structure, a diligent mentorship program, persistent execution of best practices, and an in-house mechanism for continuous improvement. As pioneers in the Drupal community we regularly present at DrupalCon and DrupalCamp conferences worldwide. Employees are encouraged to contribute to the Open Source community on company time.

**Comment by RachelBaram** [comment]
Can you also include the link to Shoov.io in the Meticulous Execution section. Thanks.

**Comment by YaronMiro** [comment]
* [x] Adding latest text. ^^
* [ ] Adding new design (Desktop & Mobile).

**Comment by YaronMiro** [comment]
@amitaibu I would like to get your opinon regarding the design.
Thanks.

![homepage](https://cloud.githubusercontent.com/assets/3907724/12550161/92f824c2-c36a-11e5-82d7-00fa8afa716f.jpg)
