### ISSUE TITLE
Fix inconsistent blog design

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#259]
You worked on this with Keren (I lost track of all the comments and changes). From what I see, the design used inside the specific blogs (blue headlines, etc) needs to be applied also to the homepage blog teaser and blog roll. 

cc @niryariv

**Comment by amitaibu** [comment]
can you please assign directly to Miro

**Comment by RachelBaram** [comment]
Will do. I just first wanted to know if this is consistent with the design decisions you made with Keren.
