### ISSUE TITLE
'TALK TO US' changes

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#260]
- [x]  'TALK TO US' needs to be the same size and font as the other headlines (FROM OUR BLOG, ABOUT US)
- [x] Replace the contact information with the following (same placement):

**Israel Headquarters**
5 Brenner St. 
Tel Aviv
+972 3 373-1222
info@gizra.com

**United States Office**
120 W 105th St. 
New York, NY 10025
+1 347 686-4508
usoffice@gizra.com

cc @niryariv  @amitaibu

**Comment by YaronMiro** [comment]
![selection_027](https://cloud.githubusercontent.com/assets/3907724/11905399/023ec9a8-a5cf-11e5-8506-1de0610775e5.png)

Currently we only have a twitter link. This is just an example if we will have multiple social links style

Resolved on #266
