### ISSUE TITLE
'The About Story' page design

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#262]
Change design to match the rest of the website.

@amitaibu - How about asking Keren to create an image for the top - maybe the little orange person in the window of an unsteady building sitting on top of the mountain?

cc @niryariv

**Comment by amitaibu** [comment]
I'd advocate against it, but lets discuss :)

**Comment by RachelBaram** [comment]
Spoke with Amitai: We will keep the unique design but must do something to make it easier to read.
