### ISSUE TITLE
Advertising space utilization

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/Gizra#276]
In the carousel and in the ```"YOU MAY HAVE SEEN OUR WORK BEFORE"``` 
We have the same companies.

I think we could make more use of the area site.

![gizra](https://cloud.githubusercontent.com/assets/5812423/12048835/c44a5964-aee8-11e5-9e13-5575b5bad706.png)

*Feel free to close the issue.

**Comment by amitaibu** [comment]
> Feel free to close the issue.

Feeling free ;)
