### ISSUE TITLE
Card Layout for Blog

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#279]
We would like to move to a card layout for the blog. This will visually make linking specific blogs to other pages nicer (i.e- all the blogs about elm linked to the elm services page).

An example:

![pasted_image_1_3_16__8_27_am](https://cloud.githubusercontent.com/assets/165644/12077557/004dfa98-b1f4-11e5-9d48-4dc1a89e32d2.png)

cc @bricel @amitaibu @niryariv

**Comment by YaronMiro** [comment]
developmentseed.com

**Comment by YaronMiro** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/3907724/12078543/0b3a1736-b21f-11e5-80ff-02ffcb8515ff.png)

**Comment by bricel** [comment]
http://jekyllrb.com/docs/plugins/
https://github.com/merlos/jekyll-auto-image
https://github.com/wildlyinaccurate/jekyll-responsive-image

**Comment by YaronMiro** [comment]
* [ ] Blog post teaser image add full title on hover using the title attribute.
* [ ] Blog page add h1 title blog
* [ ] Team page add the team as the h1 title
* [ ] Homepage Gizra is h1
* [ ] Blog post full page the Gizra logo is h2 and the title is h1
* [ ] Add LinkedIn social on footer
* [ ] Add issue to add a default picture for each post

**Comment by YaronMiro** [comment]
Ussing images from https://stocksnap.io/ **Free to use**

**Comment by bricel** [comment]
@RachelBaram Still work in progress but here is a preview:

![image](https://cloud.githubusercontent.com/assets/165644/12165650/539737e6-b528-11e5-8025-4852ced5ea1a.png)

**Comment by RachelBaram** [comment]
Nice!
