### ISSUE TITLE
Service page elm

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra#283]
- [x] Display teasers of blogs that have the relevant tags (show all the teasers of all the blogs that talk about elm) 
- [ ] - Add link to service page on the post full page.
- [x] Display Related projects block ( Project teaser - title and an image) .
- [x] Optional Text block about the technology/subject ( e.g. elm).
- [x] Text block about the service (e.g drupal).

**Comment by YaronMiro** [comment]
@RachelBaram, @bricel  the service page text is wip needs to be updated to more relevant text.
thanks.
