### ISSUE TITLE
Team member personal page

### ISSUE THREAD

**Issue by YaronMiro** [Gizra/Gizra#297]
* [ ] member image.
* [ ] member info.
* [ ] all blog posts by this member (with pager)

**Comment by amitaibu** [comment]
I don't think this is really needed.

**Comment by YaronMiro** [comment]
@amitaibu 
This is not a top priority and we should discuss if we want to add such a feature :)
It doesn't have to be an info page but at-least some page where you can view blog-post by an author. 

From my personal experience when I encounter a good blog post then I'm always intrigued to check more posts from the author.
