### ISSUE TITLE
Remove "View our blog" button

### ISSUE THREAD

**Issue by amitaibu** [Gizra/Gizra#300]
@YaronMiro Maybe, we can make the title a link to the blog teasers instead -  what do you think?

![design___web_development___gizra](https://cloud.githubusercontent.com/assets/125707/12223277/3c99f4ec-b7db-11e5-94be-6852ff58793e.jpg)

**Comment by amitaibu** [comment]
(btw, the card layout looks really great)

**Comment by YaronMiro** [comment]
Resolved on #283
