### ISSUE TITLE
Add Jobs page

### ISSUE THREAD

**Issue by amitaibu** [Gizra/Gizra#323]
https://gist.github.com/amitaibu/aa7836924e2bc0acd834

**Comment by DavidKohav** [comment]
@amitaibu - Hi
Who do you want to take responsibility for the task?

**Comment by amitaibu** [comment]
It is contribution, so who ever wants to pick it up

**Comment by DavidKohav** [comment]
@amitaibu - 
Maby it's better to merge it with the team page, in the footer.
What you prefer ?

**Comment by amitaibu** [comment]
No, it should be its own page

**Comment by DavidKohav** [comment]
:+1:

**Comment by amitaibu** [comment]
Lets create a page under `/jobs/experienced-web-dev`, with the text from [here](https://gist.github.com/amitaibu/aa7836924e2bc0acd834)

**Comment by DavidKohav** [comment]
Hi,
Can you please let me know how the users get to this page from the homepage?

**Comment by amitaibu** [comment]
they can't. for now they are redirected from facebook there. We'll address a proper Jobs section in the near future.
