### ISSUE TITLE
Use CSS to make title upper case

### ISSUE THREAD

**Issue by amitaibu** [Gizra/Gizra#354]
![cross-site_scripting_attack_detection](https://cloud.githubusercontent.com/assets/125707/13858257/7db94182-ec86-11e5-9db5-26938b5d69de.jpg)

**Comment by guytepper** [comment]
What do you mean? It's already using `text-transform: uppercase`

**Comment by amitaibu** [comment]
Sorry, my mistake-  I thought it was doing the upper case via Jekyll's template system.
