### ISSUE TITLE
Need to remove employee from the team.

### ISSUE THREAD

**Issue by DavidKohav** [Gizra/Gizra#370]
![selection_004](https://cloud.githubusercontent.com/assets/5812423/14101833/aa2ea230-f59f-11e5-8d61-113cd97fede2.png)

Need to remove eploye from the them

**Comment by amitaibu** [comment]
@DavidKohav feel free to self-assign those issues

**Comment by DavidKohav** [comment]
Ok :+1:

**Comment by DavidKohav** [comment]
Merged!
