### ISSUE TITLE
Add Image to viral job posting blog post

### ISSUE THREAD

**Issue by IshaDakota** [Gizra/Gizra#382]
Can we add an image to this blog post (maybe a screenshot of the original facebook post) so that it appears alongside social media shares.

http://www.gizra.com/content/job-post-goes-viral/

I guess also related to #371 - so that the thumbnail image would appear.

**Comment by amitaibu** [comment]
Care to create a PR? :)

**Comment by IshaDakota** [comment]
sure.

**Comment by amitaibu** [comment]
Deployed.
